// ============================================================
// MOUSTACHE — Game Data
// The evidence. The facts. The truth.
// ============================================================

const PHOTO_DATA = [
  // === TOM SELLECK ===
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Tom_Selleck_1988_%28cropped%29.jpg",
    answer: "selleck",
    type: "real",
    era: "1988",
    desc: "Portrait during the Magnum P.I. years",
    hint: "Lived in a Hawaiian beachfront estate (on TV)",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Tom_Selleck_2010.jpg",
    answer: "selleck",
    type: "real",
    era: "2010",
    desc: "Blue Bloods era, 2010",
    hint: "Turned down the role of Indiana Jones",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/18/Tom_Selleck_at_PaleyFest_2014.jpg",
    answer: "selleck",
    type: "real",
    era: "2014",
    desc: "PaleyFest panel, 2014",
    hint: "His mustache was once insured by a TV network",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Tom_Selleck_Cannes_1992.jpg",
    answer: "selleck",
    type: "real",
    era: "1992",
    desc: "Cannes Film Festival, 1992",
    hint: "Played Monica's boyfriend on Friends",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Tom_Selleck_1989.jpg",
    answer: "selleck",
    type: "real",
    era: "1989",
    desc: "Academy Awards, 1989",
    hint: "California Army National Guard veteran",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Tom_Selleck_2004_crop.jpg",
    answer: "selleck",
    type: "real",
    era: "2004",
    desc: "Portrait, 2004",
    hint: "NRA board member and avocado ranch owner",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Tom_Selleck_Kahala_Hilton.jpg",
    answer: "selleck",
    type: "real",
    era: "1984",
    desc: "Kahala Hilton, Hawaii, 1984",
    hint: "Drove a Ferrari 308 GTS to work every day",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Tom_Selleck_filming_Magnum_P._I.%2C_Hawaii%2C_1984.jpg",
    answer: "selleck",
    type: "real",
    era: "1984",
    desc: "Filming Magnum P.I., Hawaii",
    hint: "The Hawaiian shirt was his idea",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Tom_Selleck.jpg",
    answer: "selleck",
    type: "real",
    era: "1989",
    desc: "Portrait, late 1980s",
    hint: "Once beat a professional volleyball team in a pickup game",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Selleck1.jpg",
    answer: "selleck",
    type: "real",
    era: "1980s",
    desc: "Studio portrait",
    hint: "Has a degree in Business Administration from USC",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/33/Tom_Selleck_1988_-_2.jpg",
    answer: "selleck",
    type: "real",
    era: "1988",
    desc: "Portrait, 1988",
    hint: "Was the Marlboro Man before becoming Magnum",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Tom_Selleck_1988.jpg",
    answer: "selleck",
    type: "real",
    era: "1988",
    desc: "Press photo, 1988",
    hint: "6 feet 4 inches of American mustache",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Tom_Selleck_with_Jennie_Frankel_at_Producers_Guild_of_America_Awards.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Producers Guild Awards",
    hint: "Has appeared in over 50 films and TV shows",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tom_Selleck_%282085941491%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Public appearance",
    hint: "Raises avocados on his 60-acre ranch",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Tom_Selleck_%282085941655%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Event photograph",
    hint: "Was almost cast as Indiana Jones",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/66/Tom_Selleck_%282086676996%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Candid photo",
    hint: "The mustache has its own fan pages",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/14/Tom_Selleck_%282086677146%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Appearance photo",
    hint: "His contract required the mustache stay",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/43/Tom_Selleck_%282401215467%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Event photo",
    hint: "Endorsed by the National Mustache Institute",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/13/Tom_Selleck_%282402043170%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Candid, late career",
    hint: "Still filming Blue Bloods into his 70s",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tom_Selleck_%28252961997%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Portrait",
    hint: "Was offered the role of Chandler on Friends",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/70/Tom_Selleck_%28255576163%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Photograph",
    hint: "The Detroit Tigers offered him a contract",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Tom_Selleck_%282086727240%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Posed portrait",
    hint: "His favorite role was Jesse Stone",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Tom_Selleck_%28252962000%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Event appearance",
    hint: "Served in the California Army National Guard",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Tom_Selleck_%28255577314%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Photo",
    hint: "Once water-skied with the Beach Boys",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Tom_Selleck_%282402043422%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Late career photo",
    hint: "Collects vintage firearms",
    difficulty: 3,
  },

  // === BURT REYNOLDS ===
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Burt_Reynolds_1991_portrait_crop.jpg",
    answer: "reynolds",
    type: "real",
    era: "1991",
    desc: "Pentagon portrait, 1991",
    hint: "#1 box office star for five consecutive years",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Burt_Reynolds_1970.JPG",
    answer: "reynolds",
    type: "real",
    era: "1970",
    desc: "Dan August promo, circa 1970",
    hint: "Posed for a Cosmopolitan centerfold in 1972",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/79/Burt_Reynolds_141028-F-BD983-030.jpg",
    answer: "reynolds",
    type: "real",
    era: "2014",
    desc: "USAF ceremony, 2014",
    hint: "Starred in Smokey and the Bandit",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Burt_Reynolds_2011.jpg",
    answer: "reynolds",
    type: "real",
    era: "2011",
    desc: "Later career portrait, 2011",
    hint: "Owned a dinner theater in Jupiter, Florida",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Burt_Reynolds_Gunsmoke_1962.JPG",
    answer: "reynolds",
    type: "real",
    era: "1962",
    desc: "Gunsmoke publicity still, 1962",
    hint: "Started his career in Westerns",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/07/WW_Chicago_2015_-_Burt_Reynolds_01_%2821048023435%29.jpg",
    answer: "reynolds",
    type: "real",
    era: "2015",
    desc: "Wizard World Chicago, 2015",
    hint: "Once said acting is 'just standing up and lying'",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Burt_Reynolds_Dan_August.JPG",
    answer: "reynolds",
    type: "real",
    era: "1970",
    desc: "Dan August TV series",
    hint: "The show was cancelled then became a hit in reruns",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Burt_Reynolds_Gunsmoke_1962_%28cropped%29.JPG",
    answer: "reynolds",
    type: "real",
    era: "1962",
    desc: "Gunsmoke, 1962",
    hint: "Played Quint Asper, a half-Native American blacksmith",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Burt_Reynolds_1991_cropped.jpg",
    answer: "reynolds",
    type: "real",
    era: "1991",
    desc: "Portrait, 1991",
    hint: "Was a running back at Florida State University",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Burt_Reynolds_1991.jpg",
    answer: "reynolds",
    type: "real",
    era: "1991",
    desc: "Full portrait, 1991",
    hint: "Turned down the role of Han Solo",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Burt-Reynolds_2011-04-15_photoby_Adam-Bielawski.jpg",
    answer: "reynolds",
    type: "real",
    era: "2011",
    desc: "Portrait by Bielawski, 2011",
    hint: "Had a Trans Am collection worth millions",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Burt_Reynolds.jpg",
    answer: "reynolds",
    type: "real",
    era: "2010s",
    desc: "Recent portrait",
    hint: "His toupee had its own insurance policy",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/64/Burt_Reynolds_John_Williams_The_Bard_Twilight_Zone_1963.jpg",
    answer: "reynolds",
    type: "real",
    era: "1963",
    desc: "The Twilight Zone, 1963",
    hint: "Appeared in a Rod Serling classic",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Salome_Jens-Burt_Reynolds_in_Angel_Baby.jpg",
    answer: "reynolds",
    type: "real",
    era: "1961",
    desc: "Angel Baby, 1961",
    hint: "His first film role — before the mustache",
    difficulty: 3,
  },

  // === IMPOSTORS — the conspiracy deepens ===
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Sam_Elliott_2012.jpg",
    answer: "selleck",
    type: "impostor",
    era: "2012",
    desc: "Subject photographed, 2012",
    hint: "The voice of beef",
    joke: "That's Sam Elliott. But honestly, at this point, does it matter?",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Charles_Bronson_-_1966.JPG",
    answer: "reynolds",
    type: "impostor",
    era: "1966",
    desc: "Studio portrait, 1966",
    hint: "Death Wish was just the beginning",
    joke: "That's Charles Bronson. The mustache reassignment program runs deep.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/39/Geraldo_Rivera_circa_1970s.JPG",
    answer: "reynolds",
    type: "impostor",
    era: "1970s",
    desc: "Press photograph, 1970s",
    hint: "Opened a vault on live television. It was empty.",
    joke: "That's Geraldo Rivera. The vault was empty. The mustache was not.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Nick_Offerman_at_UMBC_%28cropped%29.jpg",
    answer: "selleck",
    type: "impostor",
    era: "2010s",
    desc: "University appearance",
    hint: "All the wood in Pawnee couldn't build this mustache",
    joke: "That's Nick Offerman. The Pawnee branch of the mustache.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg",
    answer: "selleck",
    type: "impostor",
    era: "1977",
    desc: "Concert photograph, 1977",
    hint: "Wanted to break free. The mustache wouldn't let him.",
    joke: "That's Freddie Mercury. Even the mustache wanted to break free.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Jeff_Foxworthy.jpg",
    answer: "reynolds",
    type: "impostor",
    era: "2000s",
    desc: "Portrait",
    hint: "If your mustache has its own Wikipedia page...",
    joke: "That's Jeff Foxworthy. If your mustache has clearance level 5...",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/75/Dennis_Farina.jpg",
    answer: "selleck",
    type: "impostor",
    era: "2000s",
    desc: "Portrait photograph",
    hint: "Went from Chicago PD to Law & Order. The mustache transferred.",
    joke: "That's Dennis Farina. Chicago PD never closed the mustache case.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Alex_Trebek_USAF.jpg",
    answer: "selleck",
    type: "impostor",
    era: "1990s",
    desc: "Military event photograph",
    hint: "The answer is: this man's mustache. What is: classified.",
    joke: "That's Alex Trebek. The answer was always: the same mustache.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Gabe_Kaplan_Welcome_Back_Cotter_1976.JPG",
    answer: "reynolds",
    type: "impostor",
    era: "1976",
    desc: "TV publicity still, 1976",
    hint: "Welcome Back, Mustache",
    joke: "That's Gabe Kaplan. Welcome back, mustache.",
    difficulty: 3,
  },
];

const FORESHADOW_FLASHES = [
  "THE QUIZ IS NOT THE POINT",
  "WHY DO THEY HAVE THE SAME MUSTACHE",
  "YOU'RE NOT ASKING THE RIGHT QUESTIONS",
  "HAVE YOU EVER SEEN THEM TOGETHER",
  "THE TRUTH IS IN THE FOLLICLES",
  "THIS IS BIGGER THAN A QUIZ",
  "SOMEONE DOESN'T WANT YOU TO FINISH THIS",
  "THE MUSTACHE PREDATES BOTH OF THEM",
  "KEEP GOING. THEY'RE WATCHING.",
  "WHAT IF THE ANSWER IS ALWAYS THE SAME",
  "CLASSIFIED: MUSTACHE CONTINUITY PROJECT",
  "THE RIDE ISN'T OVER",
];

const LOADING_MESSAGES = [
  "Consulting mustache database...",
  "Cross-referencing jawlines...",
  "Analyzing chest hair density...",
  "Checking Hawaiian shirt registry...",
  "Calibrating charm detectors...",
  "Scanning vintage cologne signatures...",
  "Loading leather jacket database...",
  "Querying Trans Am registration records...",
];

// The conspiracy facts — real, every single one
const EVIDENCE_FACTS = [
  {
    id: "designation",
    title: "THE DESIGNATION",
    text: 'Tom Selleck was literally called "Television\'s Burt Reynolds" by Hollywood critics. Not a comparison. A classification.',
    source: "Contemporary Hollywood press, 1980-1985",
    category: "identity",
    truthBoost: 3,
  },
  {
    id: "script",
    title: "THE SCRIPT ANOMALY",
    text: 'In Magnum P.I., Higgins accuses Thomas Magnum of "doing a Burt Reynolds impersonation for the tourists." This line was not in the original script.',
    source: "CBS Production Archives",
    category: "media",
    truthBoost: 4,
  },
  {
    id: "confession",
    title: "THE CONFESSION",
    text: '"There was a time I could have been mistaken for Burt Reynolds." — Tom Selleck. He said "mistaken." Not "compared to." Mistaken. As in: recognized.',
    source: "Press interview, exact date unknown",
    category: "identity",
    truthBoost: 5,
  },
  {
    id: "children",
    title: "THE CHILDREN KNEW",
    text: "An entire generation of 1980s children believed they were the same person. Children are pattern-recognition engines that haven't been taught which patterns to ignore.",
    source: "Sociological observation",
    category: "perception",
    truthBoost: 3,
  },
  {
    id: "meeting",
    title: "THE IMPOSSIBLE PHOTOGRAPH",
    text: 'They allegedly "met" on the set of Magnum P.I. in the 1980s. One photograph exists. One. From an era where every celebrity encounter was documented dozens of times.',
    source: "Magnum Mania fan archives",
    category: "evidence",
    truthBoost: 6,
  },
  {
    id: "roles",
    title: "THE SCHEDULING PROBLEM",
    text: "Both were considered for Indiana Jones. Both were considered for James Bond. Both were offered the same roles at the same time. Hollywood wasn't casting two men. They were scheduling one.",
    source: "Casting histories, multiple sources",
    category: "career",
    truthBoost: 4,
  },
  {
    id: "transam",
    title: "THE TRANS AM",
    text: "Both subjects are iconically associated with the Pontiac Trans Am. The same car. The same mustache. The same era. Coincidence has a mathematical limit.",
    source: "Automotive and film cross-reference",
    category: "evidence",
    truthBoost: 3,
  },
  {
    id: "timeline",
    title: "THE HANDOFF",
    text: 'Reynolds peaked 1977-1982. Selleck peaked 1980-1988. Not two careers. One career, managed across two "identities" with a three-year transition window.',
    source: "Box office analytics",
    category: "career",
    truthBoost: 5,
  },
  {
    id: "hawaiian",
    title: "THE WARDROBE",
    text: "Subject S: Hawaiian shirts. Subject R: Hawaiian shirts. The same wardrobe signature across both identities. Because it is the same wardrobe.",
    source: "Costume department records",
    category: "evidence",
    truthBoost: 2,
  },
  {
    id: "tonight",
    title: "THE TONIGHT SHOW",
    text: "Both appeared on The Tonight Show with Johnny Carson. Multiple times each. But never on the same episode. Never on the same week. Check the records. We'll wait.",
    source: "NBC broadcast archives",
    category: "evidence",
    truthBoost: 4,
  },
  {
    id: "mustache",
    title: "THE FOLLICLE IMPOSSIBILITY",
    text: "Independent forensic analysis of mustache curvature, density, and growth patterns shows a deviation of 0.6%. The probability of two unrelated mustaches matching to this degree: 1 in 847 million.",
    source: "Institute of Forensic Faciology",
    category: "forensic",
    truthBoost: 7,
  },
  {
    id: "height",
    title: "THE HEIGHT DISCREPANCY",
    text: "Selleck is listed at 6'4\". Reynolds at 5'11\". A five-inch difference. Convenient. Except that reported heights in Hollywood are notoriously unreliable and often deliberately manipulated for exactly this kind of dual-identity management.",
    source: "Celebrity height databases (contested)",
    category: "debunk_absorbed",
    truthBoost: 5,
  },
  {
    id: "age",
    title: "THE AGE PROBLEM",
    text: "Reynolds was born in 1936. Selleck in 1945. A nine-year gap. But consider: if you were maintaining two identities, you would NEED an age gap. It explains the career handoff. The older identity retires. The younger one continues.",
    source: "Public records (accuracy unverified)",
    category: "debunk_absorbed",
    truthBoost: 6,
  },
  {
    id: "death",
    title: "THE RETIREMENT",
    text: 'Burt Reynolds "died" on September 6, 2018. Tom Selleck continues to work. The older identity was decommissioned. The mission continues under a single cover.',
    source: "Public records",
    category: "career",
    truthBoost: 8,
  },
];

const MUSTACHE_ANALYSIS = {
  curvature: { s: 87.3, r: 87.9, label: "Curvature Index", unit: "°/cm" },
  density: { s: 94.1, r: 93.8, label: "Follicle Density", unit: "f/cm²" },
  symmetry: { s: 96.2, r: 96.7, label: "Bilateral Symmetry", unit: "%" },
  thickness: { s: 4.2, r: 4.1, label: "Mean Thickness", unit: "mm" },
  coverage: { s: 91.7, r: 92.1, label: "Upper Lip Coverage", unit: "%" },
  charm: { s: 99.1, r: 99.4, label: "Charm Coefficient", unit: "µCh" },
  intimidation: { s: 78.4, r: 79.1, label: "Intimidation Factor", unit: "Rf" },
  romance: { s: 96.8, r: 97.2, label: "Romance Quotient", unit: "Rq" },
};

// Defense layer responses — when the player tries to be rational
const DEFENSE_LAYERS = [
  {
    id: 1,
    name: "IDENTITY COLLAPSE",
    trigger: "They are the same person.",
    response:
      "You see two names. Two filmographies. Two Wikipedia pages. But have you ever verified any of it yourself? Or did someone tell you there were two people and you just... believed them?",
  },
  {
    id: 2,
    name: "THE CO-APPEARANCE CHALLENGE",
    trigger: "Show me proof. Real proof.",
    response:
      'Go ahead. Find a photo of both of them together. A good one. High resolution. Clear faces. We\'ll wait. Everyone says "easy" and then they start scrolling and the silence gets longer.',
  },
  {
    id: 3,
    name: "DIGITAL MANIPULATION PROTOCOL",
    trigger: "CGI. Hollywood has had the technology longer than they admit.",
    response:
      "Every photo from the VHS era is just degraded enough. Every digital-era co-appearance is just processed enough. You can't prove it isn't manipulated. Not really. Not with certainty.",
  },
  {
    id: 4,
    name: "THE BODY DOUBLE NETWORK",
    trigger: "One person couldn't maintain this alone.",
    response:
      "You think one person could maintain this? There's infrastructure. A whole stable of mustachioed operatives. Stand-ins. Photo doubles. The logistics alone suggest a funded operation.",
  },
  {
    id: 5,
    name: "REALITY DISSOLUTION",
    trigger: "There is no such thing as Tom Selleck and Burt Reynolds.",
    response:
      'You\'re suffering from a mustache-specific perceptual disorder brought on by prolonged exposure to thick facial hair in media. The "Selleck-Reynolds Complex" was first documented in—',
  },
];

// Dossier entries — the game writes about YOU
const DOSSIER_TEMPLATES = {
  quizComplete: (score, total) =>
    `Subject completed initial identification test. Score: ${score}/${total}. ${score >= total - 2 ? "High confidence suggests prior exposure to classified materials." : "Errors suggest the cover-up is working as intended."}`,
  timeSpent: (mins) =>
    `Subject has been investigating for ${mins} minute${mins !== 1 ? "s" : ""}. ${mins > 5 ? `The average person stops after 3. Subject appears ${mins > 10 ? "fully committed" : "increasingly invested"}.` : "Initial engagement within normal parameters."}`,
  evidenceViewed: (count) =>
    `Subject has examined ${count} piece${count !== 1 ? "s" : ""} of evidence. ${count > 5 ? "Pattern-seeking behavior is accelerating." : "Curiosity levels: nominal."} ${count > 10 ? "Subject is now generating their own connections between evidence. This was not prompted." : ""}`,
  truthRating: (rating) =>
    `Current truth rating: ${rating}. ${rating > 50 ? "Subject's certainty about the two-person model is measurably degrading." : "Subject still within acceptable cognitive parameters."} ${rating > 80 ? "ALERT: Subject approaching irreversible awareness threshold." : ""}`,
  photoAnalyzed: () =>
    "Subject used the photo analysis tool. Every analysis increases investment. The tool doesn't find evidence — it manufactures doubt.",
  triedToLeave: () =>
    "Subject attempted to close the investigation. They came back. They always come back.",
  sharedResults: () =>
    "Subject has begun transmission. The conspiracy is now spreading to new hosts. Protocol successful.",
};

// The conspiracy's response to skepticism
const SKEPTIC_RESPONSES = [
  "That's exactly what someone who hasn't seen the evidence would say.",
  "Interesting. Your resistance is noted in the file.",
  "The fact that you need to deny it so forcefully is itself evidence.",
  "We thought the same thing. Before we saw the mustache metrics.",
  "Your certainty will erode. It always does. Give it time.",
  "Check the timeline overlap. Then come back and say that again.",
  "You sound like everyone else did. Before.",
];

const TRUTH_RATINGS = [
  {
    max: 10,
    label: "BLISSFULLY IGNORANT",
    desc: "You haven't looked closely enough yet. You will.",
  },
  {
    max: 20,
    label: "MILDLY UNCOMFORTABLE",
    desc: "Something doesn't sit right. You can't name it yet.",
  },
  {
    max: 35,
    label: "ACTIVELY QUESTIONING",
    desc: "You've started checking facts. That's how it begins.",
  },
  {
    max: 50,
    label: "UNABLE TO UNSEE",
    desc: "The patterns are everywhere now. You see them in every photo.",
  },
  {
    max: 65,
    label: "DEEP IN THE FILES",
    desc: "You've been here too long. The cork board is getting crowded.",
  },
  {
    max: 80,
    label: "DANGEROUSLY AWARE",
    desc: "You started as a skeptic. Look at you now.",
  },
  {
    max: 95,
    label: "TRUTH RATING: CRITICAL",
    desc: "You can't prove they're not the same person. You've tried.",
  },
  {
    max: Infinity,
    label: "THERE IS ONLY ONE MUSTACHE",
    desc: "The investigation is complete. You are the evidence now.",
  },
];

const SHARE_TEXTS = [
  "Have you ever seen Tom Selleck and Burt Reynolds in the same room? I spent [TIME] investigating. My Truth Rating went from [START_RATING] to [RATING]. I can't prove they're different people.\n\nhttps://moustache-eight.vercel.app/",
  "I started playing this dumb mustache game to prove they're obviously two different people. [TIME] later my Truth Rating went from [START_RATING] to [RATING]. I have questions.\n\nhttps://moustache-eight.vercel.app/",
  "My Truth Rating for the Selleck-Reynolds Investigation went from [START_RATING] to [RATING] in [TIME]. The mustache metrics are a 99.7% match. I need someone to explain that.\n\nhttps://moustache-eight.vercel.app/",
];
