// ============================================================
// MOUSTACHE — Game Data
// The evidence. The facts. The truth.
// ============================================================

const PHOTO_DATA = [
  // === TOM SELLECK ===
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Tom_Selleck_1988_%28cropped%29.jpg",
    answer: "selleck",
    type: "real",
    era: "1988",
    desc: "Portrait during the Magnum P.I. years",
    hint: "Lived in a Hawaiian beachfront estate (on TV)",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Tom_Selleck_2010.jpg",
    answer: "selleck",
    type: "real",
    era: "2010",
    desc: "Blue Bloods era, 2010",
    hint: "Turned down the role of Indiana Jones",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/18/Tom_Selleck_at_PaleyFest_2014.jpg",
    answer: "selleck",
    type: "real",
    era: "2014",
    desc: "PaleyFest panel, 2014",
    hint: "His moustache was once insured by a TV network",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Tom_Selleck_Cannes_1992.jpg",
    answer: "selleck",
    type: "real",
    era: "1992",
    desc: "Cannes Film Festival, 1992",
    hint: "Played Monica's boyfriend on Friends",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Tom_Selleck_1989.jpg",
    answer: "selleck",
    type: "real",
    era: "1989",
    desc: "Academy Awards, 1989",
    hint: "California Army National Guard veteran",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Tom_Selleck_2004_crop.jpg",
    answer: "selleck",
    type: "real",
    era: "2004",
    desc: "Portrait, 2004",
    hint: "NRA board member and avocado ranch owner",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Tom_Selleck_Kahala_Hilton.jpg",
    answer: "selleck",
    type: "real",
    era: "1984",
    desc: "Kahala Hilton, Hawaii, 1984",
    hint: "Drove a Ferrari 308 GTS to work every day",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Tom_Selleck_filming_Magnum_P._I.%2C_Hawaii%2C_1984.jpg",
    answer: "selleck",
    type: "real",
    era: "1984",
    desc: "Filming Magnum P.I., Hawaii",
    hint: "The Hawaiian shirt was his idea",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Tom_Selleck.jpg",
    answer: "selleck",
    type: "real",
    era: "1989",
    desc: "Portrait, late 1980s",
    hint: "Once beat a professional volleyball team in a pickup game",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Selleck1.jpg",
    answer: "selleck",
    type: "real",
    era: "1980s",
    desc: "Studio portrait",
    hint: "Has a degree in Business Administration from USC",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/33/Tom_Selleck_1988_-_2.jpg",
    answer: "selleck",
    type: "real",
    era: "1988",
    desc: "Portrait, 1988",
    hint: "Was the Marlboro Man before becoming Magnum",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Tom_Selleck_1988.jpg",
    answer: "selleck",
    type: "real",
    era: "1988",
    desc: "Press photo, 1988",
    hint: "6 feet 4 inches of American moustache",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Tom_Selleck_with_Jennie_Frankel_at_Producers_Guild_of_America_Awards.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Producers Guild Awards",
    hint: "Has appeared in over 50 films and TV shows",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tom_Selleck_%282085941491%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Public appearance",
    hint: "Raises avocados on his 60-acre ranch",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Tom_Selleck_%282085941655%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Event photograph",
    hint: "Was almost cast as Indiana Jones",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/66/Tom_Selleck_%282086676996%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Candid photo",
    hint: "The moustache has its own fan pages",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/14/Tom_Selleck_%282086677146%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Appearance photo",
    hint: "His contract required the moustache stay",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/43/Tom_Selleck_%282401215467%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Event photo",
    hint: "Endorsed by the National Moustache Institute",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/13/Tom_Selleck_%282402043170%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Candid, late career",
    hint: "Still filming Blue Bloods into his 70s",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tom_Selleck_%28252961997%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Portrait",
    hint: "Was offered the role of Chandler on Friends",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/70/Tom_Selleck_%28255576163%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Photograph",
    hint: "The Detroit Tigers offered him a contract",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Tom_Selleck_%282086727240%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Posed portrait",
    hint: "His favorite role was Jesse Stone",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Tom_Selleck_%28252962000%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Event appearance",
    hint: "Served in the California Army National Guard",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Tom_Selleck_%28255577314%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Photo",
    hint: "Once water-skied with the Beach Boys",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Tom_Selleck_%282402043422%29.jpg",
    answer: "selleck",
    type: "real",
    era: "2000s",
    desc: "Late career photo",
    hint: "Collects vintage firearms",
    difficulty: 3,
  },

  // === BURT REYNOLDS ===
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Burt_Reynolds_1991_portrait_crop.jpg",
    answer: "reynolds",
    type: "real",
    era: "1991",
    desc: "Pentagon portrait, 1991",
    hint: "#1 box office star for five consecutive years",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Burt_Reynolds_1970.JPG",
    answer: "reynolds",
    type: "real",
    era: "1970",
    desc: "Dan August promo, circa 1970",
    hint: "Posed for a Cosmopolitan centerfold in 1972",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/79/Burt_Reynolds_141028-F-BD983-030.jpg",
    answer: "reynolds",
    type: "real",
    era: "2014",
    desc: "USAF ceremony, 2014",
    hint: "Starred in Smokey and the Bandit",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Burt_Reynolds_2011.jpg",
    answer: "reynolds",
    type: "real",
    era: "2011",
    desc: "Later career portrait, 2011",
    hint: "Owned a dinner theater in Jupiter, Florida",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Burt_Reynolds_Gunsmoke_1962.JPG",
    answer: "reynolds",
    type: "real",
    era: "1962",
    desc: "Gunsmoke publicity still, 1962",
    hint: "Started his career in Westerns",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/07/WW_Chicago_2015_-_Burt_Reynolds_01_%2821048023435%29.jpg",
    answer: "reynolds",
    type: "real",
    era: "2015",
    desc: "Wizard World Chicago, 2015",
    hint: "Once said acting is 'just standing up and lying'",
    difficulty: 1,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Burt_Reynolds_Dan_August.JPG",
    answer: "reynolds",
    type: "real",
    era: "1970",
    desc: "Dan August TV series",
    hint: "The show was cancelled then became a hit in reruns",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Burt_Reynolds_Gunsmoke_1962_%28cropped%29.JPG",
    answer: "reynolds",
    type: "real",
    era: "1962",
    desc: "Gunsmoke, 1962",
    hint: "Played Quint Asper, a half-Native American blacksmith",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Burt_Reynolds_1991_cropped.jpg",
    answer: "reynolds",
    type: "real",
    era: "1991",
    desc: "Portrait, 1991",
    hint: "Was a running back at Florida State University",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Burt_Reynolds_1991.jpg",
    answer: "reynolds",
    type: "real",
    era: "1991",
    desc: "Full portrait, 1991",
    hint: "Turned down the role of Han Solo",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Burt-Reynolds_2011-04-15_photoby_Adam-Bielawski.jpg",
    answer: "reynolds",
    type: "real",
    era: "2011",
    desc: "Portrait by Bielawski, 2011",
    hint: "Had a Trans Am collection worth millions",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Burt_Reynolds.jpg",
    answer: "reynolds",
    type: "real",
    era: "2010s",
    desc: "Recent portrait",
    hint: "His toupee had its own insurance policy",
    difficulty: 2,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/64/Burt_Reynolds_John_Williams_The_Bard_Twilight_Zone_1963.jpg",
    answer: "reynolds",
    type: "real",
    era: "1963",
    desc: "The Twilight Zone, 1963",
    hint: "Appeared in a Rod Serling classic",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Salome_Jens-Burt_Reynolds_in_Angel_Baby.jpg",
    answer: "reynolds",
    type: "real",
    era: "1961",
    desc: "Angel Baby, 1961",
    hint: "His first film role — before the moustache",
    difficulty: 3,
  },

  // === IMPOSTORS — PLAUSIBLE TIER ===
  // These mustachioed men could genuinely confuse someone
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Sam_Elliott_2012.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Sam Elliott",
    era: "2012",
    desc: "Subject photographed, 2012",
    hint: "The voice of beef",
    joke: "The moustache matched. That's all that matters.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Charles_Bronson_-_1966.JPG",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Charles Bronson",
    era: "1966",
    desc: "Studio portrait, 1966",
    hint: "Death Wish was just the beginning",
    joke: "Something about this one felt different. Ignore that feeling.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/39/Geraldo_Rivera_circa_1970s.JPG",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Geraldo Rivera",
    era: "1970s",
    desc: "Press photograph, 1970s",
    hint: "Opened a vault on live television. It was empty.",
    joke: "Did that face look right to you? Don't answer that.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Nick_Offerman_at_UMBC_%28cropped%29.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Nick Offerman",
    era: "2010s",
    desc: "University appearance",
    hint: "All the wood in Pawnee couldn't build this moustache",
    joke: "The moustache is correct. The man behind it is... irrelevant.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Freddie Mercury",
    era: "1977",
    desc: "Concert photograph, 1977",
    hint: "Wanted to break free. The moustache wouldn't let him.",
    joke: "You hesitated. That's interesting.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Jeff_Foxworthy.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Jeff Foxworthy",
    era: "2000s",
    desc: "Portrait",
    hint: "If your moustache has its own Wikipedia page...",
    joke: "Correct is correct. Don't overthink it.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/75/Dennis_Farina.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Dennis Farina",
    era: "2000s",
    desc: "Portrait photograph",
    hint: "Went from Chicago PD to Law & Order. The moustache transferred.",
    joke: "The eyes were wrong but the moustache was right. Move on.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Alex_Trebek_USAF.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Alex Trebek",
    era: "1990s",
    desc: "Military event photograph",
    hint: "The answer is: this man's moustache. What is: classified.",
    joke: "You got it right. Why does it feel like you didn't?",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Gabe_Kaplan_Welcome_Back_Cotter_1976.JPG",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Gabe Kaplan",
    era: "1976",
    desc: "TV publicity still, 1976",
    hint: "Welcome Back, Moustache",
    joke: "That one didn't look like either of them. But it did, didn't it?",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/00/Mark_Spitz_1972.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Mark Spitz",
    era: "1972",
    desc: "Olympic portrait, 1972",
    hint: "Seven golds. One moustache. Zero coincidences.",
    joke: "The chlorine couldn't wash away the resemblance.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Cheech_Marin_by_Gage_Skidmore.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Cheech Marin",
    era: "2010s",
    desc: "Convention appearance",
    hint: "Dave's not here, man. But the moustache is.",
    joke: "Up in Smoke. Like the truth.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Gene_Shalit_March_1986_%28headshot%29.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Gene Shalit",
    era: "1986",
    desc: "Headshot, March 1986",
    hint: "His moustache reviewed movies. The movies never recovered.",
    joke: "Two thumbs up for that moustache. Everything else is classified.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/61/Keith_Hernandez_-_St._Louis_Cardinals.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Keith Hernandez",
    era: "1980s",
    desc: "Baseball card photograph",
    hint: "Nice game, pretty boy",
    joke: "The moustache made the All-Star team. The man was just along for the ride.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/12/JohnOatesByPhilKonstantin.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "John Oates",
    era: "2008",
    desc: "Portrait photograph",
    hint: "Your kiss is on his list. So is his moustache.",
    joke: "I can't go for that. But the moustache can.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Danny_Trejo_by_Gage_Skidmore.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Danny Trejo",
    era: "2010s",
    desc: "Convention photograph",
    hint: "Machete don't shave",
    joke: "That moustache has killed people. In movies. Probably.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/02/Frank_Zappa_1973_2.JPG",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Frank Zappa",
    era: "1973",
    desc: "Performance photograph, 1973",
    hint: "The moustache is a conceptual continuation of the soul patch",
    joke: "You're having trouble with the moustache police.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Mike_Ditka_2008_NFL_Experience_48-DPA-02_01_02_08_%28cropped%29.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Mike Ditka",
    era: "2008",
    desc: "NFL event photograph",
    hint: "Da moustache",
    joke: "The Bears won a Super Bowl. The moustache won every day.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Lanny_McDonald.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Lanny McDonald",
    era: "1980s",
    desc: "Hockey portrait",
    hint: "The most famous moustache in hockey. And that's a competitive field.",
    joke: "That moustache has its own penalty box.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Robrt_Goulet_2000.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Robert Goulet",
    era: "2000",
    desc: "Portrait photograph",
    hint: "The baritone behind the bristles",
    joke: "That voice. That moustache. That isn't who you think it is.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/2/20/James_Brolin_1974.JPG",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "James Brolin",
    era: "1974",
    desc: "Publicity still, 1974",
    hint: "Married a Streisand. The moustache approved.",
    joke: "If you thought that was Selleck, congratulations. That's the point.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Rollie_Fingers_on_July_12%2C_2013.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Rollie Fingers",
    era: "2013",
    desc: "Appearance, July 2013",
    hint: "The handlebar that saved a thousand games",
    joke: "That moustache has a better ERA than most pitchers.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/da/Sonny-Bono.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Sonny Bono",
    era: "1970s",
    desc: "Publicity photograph",
    hint: "Got you, babe. And the moustache.",
    joke: "The beat goes on. So does the moustache confusion.",
    difficulty: 3,
  },
  {
    url: "https://raw.githubusercontent.com/TophSV/moustache/main/media/impostors/jack-black-moustache-plausible.png",
    answer: "reynolds",
    type: "impostor",
    tier: "plausible",
    name: "Jack Black",
    era: "2000s",
    desc: "Subject photographed",
    hint: "This is not the greatest moustache in the world. This is just a tribute.",
    joke: "Tenacious. Like the facial hair.",
    difficulty: 3,
  },
  {
    url: "https://raw.githubusercontent.com/TophSV/moustache/main/media/impostors/ron-burgundy-moustache-plausible.png",
    answer: "selleck",
    type: "impostor",
    tier: "plausible",
    name: "Ron Burgundy",
    era: "2004",
    desc: "News anchor portrait",
    hint: "His moustache is kind of a big deal",
    joke: "60% of the time, that moustache works every time.",
    difficulty: 3,
  },

  // === IMPOSTORS — ABSURD TIER ===
  // Mascots, animals, historical figures, celebrities with fake moustaches
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Wilford_Brimley.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Wilford Brimley",
    era: "1980s",
    desc: "Publicity photograph",
    hint: "It's the right thing to do. And the tasty way to do it.",
    joke: "The walrus moustache speaks for itself. You just listened.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/ad/RP-Hulk_Hogan.JPG",
    answer: "reynolds",
    type: "impostor",
    tier: "absurd",
    name: "Hulk Hogan",
    era: "2007",
    desc: "Fan photograph",
    hint: "Whatcha gonna do when this moustache runs wild on you",
    joke: "Brother, that moustache slammed you into confusion.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Lionel_Richie_cropped.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Lionel Richie",
    era: "2010",
    desc: "Portrait photograph",
    hint: "Hello. Is it this moustache you're looking for?",
    joke: "Dancing on the ceiling. The moustache stayed grounded.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/2/27/Salvador_Dali_NYWTS.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "absurd",
    name: "Salvador Dalí",
    era: "1950s",
    desc: "Press photograph",
    hint: "The persistence of moustache",
    joke: "Surrealism is just realism that hasn't been caught yet.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Billy_Dee_Williams_Photo_Op_GalaxyCon_Raleigh_2023.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Billy Dee Williams",
    era: "2023",
    desc: "Convention photograph",
    hint: "Works every time",
    joke: "This deal is getting worse all the time. Like your confidence.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Albert_Einstein_Head.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Albert Einstein",
    era: "1947",
    desc: "Portrait photograph",
    hint: "E = mc² where m = moustache and c = conspiracy",
    joke: "Relatively speaking, you had no idea.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/68/Groucho_Marx_-_portrait.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "absurd",
    name: "Groucho Marx",
    era: "1950s",
    desc: "Classic portrait",
    hint: "Outside of a dog, a moustache is man's best friend",
    joke: "I wouldn't want to belong to any moustache that would have me as a member.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Nietzsche187a.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Friedrich Nietzsche",
    era: "1875",
    desc: "Portrait photograph",
    hint: "God is dead. The moustache lives.",
    joke: "When you gaze into the moustache, the moustache gazes back.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/33/Pringles_logo.png",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Julius Pringles",
    era: "Timeless",
    desc: "Corporate portrait",
    hint: "Once you pop, the conspiracy don't stop",
    joke: "You just tried to identify a chip mascot as a human man. We're noting that.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/80/Mr_Monopoly_A74006820250206.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "absurd",
    name: "Mr. Monopoly",
    era: "Timeless",
    desc: "Board game evidence",
    hint: "Do not pass Go. Do not collect your dignity.",
    joke: "You just guessed Tom or Burt for a board game piece. The investigation is working.",
    difficulty: 3,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Mr_Peanut_sketch_1917.jpg",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Mr. Peanut",
    era: "1917",
    desc: "Original field sketch",
    hint: "A legume in a top hat. The moustache is load-bearing.",
    joke: "That's a peanut. You know that, right? You clicked anyway.",
    difficulty: 3,
  },
  {
    url: "https://raw.githubusercontent.com/TophSV/moustache/main/media/impostors/sarah-silverman-fake-moustache-emmys.jpg",
    answer: "reynolds",
    type: "impostor",
    tier: "absurd",
    name: "Sarah Silverman",
    era: "2014",
    desc: "Awards ceremony photograph",
    hint: "The moustache is a bit. Or is the bit the moustache?",
    joke: "She wore it better. Than both of them.",
    difficulty: 3,
  },
  {
    url: "https://raw.githubusercontent.com/TophSV/moustache/main/media/impostors/kate-moss-finger-moustache.png",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Kate Moss",
    era: "2010s",
    desc: "Candid photograph",
    hint: "The finger moustache. A cry for help.",
    joke: "That's a supermodel doing a finger moustache. And you still guessed.",
    difficulty: 3,
  },
  {
    url: "https://raw.githubusercontent.com/TophSV/moustache/main/media/impostors/katy-perry-fake-moustache.png",
    answer: "reynolds",
    type: "impostor",
    tier: "absurd",
    name: "Katy Perry",
    era: "2010s",
    desc: "Subject in disguise",
    hint: "You're hot then you're cold then you're Tom then you're Burt",
    joke: "California Gurls don't normally need moustache identification.",
    difficulty: 3,
  },
  {
    url: "https://raw.githubusercontent.com/TophSV/moustache/main/media/impostors/justin-bieber-fake-moustache.png",
    answer: "selleck",
    type: "impostor",
    tier: "absurd",
    name: "Justin Bieber",
    era: "2010s",
    desc: "Subject photographed",
    hint: "Baby baby baby oh you thought this was Selleck",
    joke: "You just tried to ID Justin Bieber as a 1980s moustache icon. This is progress.",
    difficulty: 3,
  },
];

// Pre-answer intrusions — short, jarring, cuts in right after you click
const FORESHADOW_PRE = [
  "WHY DO THEY HAVE THE SAME MOUSTACHE",
  "HAVE YOU EVER SEEN THEM TOGETHER",
  "THE TRUTH IS IN THE FOLLICLES",
  "LOOK CLOSER",
  "THE MOUSTACHE NEVER CHANGES",
  "SAME FACE. SAME FACE. SAME FACE.",
  "WHO TOLD YOU THERE WERE TWO OF THEM",
  "THE ANSWER DOESN'T MATTER",
  "YOU ALREADY KNOW",
  "COUNT THE MOUSTACHES",
];

// Post-answer intrusions — longer, the full vision, burns in and holds
const FORESHADOW_POST = [
  "THE QUIZ IS NOT THE POINT",
  "YOU'RE NOT ASKING THE RIGHT QUESTIONS",
  "THIS IS BIGGER THAN A QUIZ",
  "SOMEONE DOESN'T WANT YOU TO FINISH THIS",
  "THE MOUSTACHE PREDATES BOTH OF THEM",
  "KEEP GOING. THEY'RE WATCHING.",
  "WHAT IF THE ANSWER IS ALWAYS THE SAME",
  "CLASSIFIED: MOUSTACHE CONTINUITY PROJECT",
  "THE RIDE ISN'T OVER",
  "THERE IS NO QUIZ. THERE IS ONLY THE MOUSTACHE.",
  "EVERY ANSWER IS CORRECT. THAT'S THE PROBLEM.",
  "YOU WERE CHOSEN FOR THIS INVESTIGATION",
];

const LOADING_MESSAGES = [
  "Consulting moustache database...",
  "Cross-referencing jawlines...",
  "Analyzing chest hair density...",
  "Checking Hawaiian shirt registry...",
  "Calibrating charm detectors...",
  "Scanning vintage cologne signatures...",
  "Loading leather jacket database...",
  "Querying Trans Am registration records...",
];

// The conspiracy facts — real, every single one
const EVIDENCE_FACTS = [
  {
    id: "designation",
    title: "THE DESIGNATION",
    text: 'Tom Selleck was literally called "Television\'s Burt Reynolds" by Hollywood critics. Not a comparison. A classification.',
    source: "Contemporary Hollywood press, 1980-1985",
    category: "identity",
    truthBoost: 3,
  },
  {
    id: "script",
    title: "THE SCRIPT ANOMALY",
    text: 'In Magnum P.I., Higgins accuses Thomas Magnum of "doing a Burt Reynolds impersonation for the tourists." This line was not in the original script. But which identity was actually behind Magnum\'s private investigations?',
    source: "CBS Production Archives",
    category: "media",
    truthBoost: 4,
  },
  {
    id: "confession",
    title: "THE CONFESSION",
    text: '"There was a time I could have been mistaken for Burt Reynolds." — Tom Selleck. He said "mistaken." Not "compared to." Mistaken. As in: recognized.',
    source: "Press interview, exact date unknown",
    category: "identity",
    truthBoost: 5,
  },
  {
    id: "children",
    title: "THE CHILDREN KNEW",
    text: "An entire generation of 1980s children believed they were the same person. Children are pattern-recognition engines that haven't been taught which patterns to ignore.",
    source: "Sociological observation",
    category: "perception",
    truthBoost: 3,
  },
  {
    id: "meeting",
    title: "THE IMPOSSIBLE PHOTOGRAPH",
    text: 'They allegedly "met" on the set of Magnum P.I. in the 1980s. One photograph exists. One. From an era where every celebrity encounter was documented dozens of times.',
    source: "Magnum Mania fan archives",
    category: "evidence",
    truthBoost: 6,
  },
  {
    id: "roles",
    title: "THE SCHEDULING PROBLEM",
    text: "Both were considered for Indiana Jones. Both were considered for James Bond. Both were offered the same roles at the same time. Hollywood wasn't casting two men. They were scheduling one.",
    source: "Casting histories, multiple sources",
    category: "career",
    truthBoost: 4,
  },
  {
    id: "transam",
    title: "THE TRANS AM",
    text: "Both subjects are iconically associated with the Pontiac Trans Am. The same car. The same moustache. The same era. Coincidence has a mathematical limit.",
    source: "Automotive and film cross-reference",
    category: "evidence",
    truthBoost: 3,
  },
  {
    id: "timeline",
    title: "THE HANDOFF",
    text: 'Reynolds peaked 1977-1982. Selleck peaked 1980-1988. Not two careers. One career, managed across two "identities" with a three-year transition window.',
    source: "Box office analytics",
    category: "career",
    truthBoost: 5,
  },
  {
    id: "hawaiian",
    title: "THE WARDROBE",
    text: "Subject S: Hawaiian shirts. Subject R: Hawaiian shirts. The same wardrobe signature across both identities. Because it is the same wardrobe.",
    source: "Costume department records",
    category: "evidence",
    truthBoost: 2,
  },
  {
    id: "tonight",
    title: "THE TONIGHT SHOW",
    text: "Both appeared on The Tonight Show with Johnny Carson. Multiple times each. But never on the same episode. Never on the same week. Check the records. We'll wait.",
    source: "NBC broadcast archives",
    category: "evidence",
    truthBoost: 4,
  },
  {
    id: "moustache",
    title: "THE FOLLICLE IMPOSSIBILITY",
    text: "Independent forensic analysis of moustache curvature, density, and growth patterns shows a deviation of 0.6%. The probability of two unrelated moustaches matching to this degree: 1 in 847 million.",
    source: "Institute of Forensic Faciology",
    category: "forensic",
    truthBoost: 7,
  },
  {
    id: "height",
    title: "THE HEIGHT DISCREPANCY",
    text: "Selleck is listed at 6'4\". Reynolds at 5'11\". A five-inch difference. Convenient. Except that reported heights in Hollywood are notoriously unreliable and often deliberately manipulated for exactly this kind of dual-identity management.",
    source: "Celebrity height databases (contested)",
    category: "debunk_absorbed",
    truthBoost: 5,
  },
  {
    id: "age",
    title: "THE AGE PROBLEM",
    text: "Reynolds was born in 1936. Selleck in 1945. A nine-year gap. But consider: if you were maintaining two identities, you would NEED an age gap. It explains the career handoff. The older identity retires. The younger one continues.",
    source: "Public records (accuracy unverified)",
    category: "debunk_absorbed",
    truthBoost: 6,
  },
  {
    id: "death",
    title: "THE RETIREMENT",
    text: 'Burt Reynolds "died" on September 6, 2018. Tom Selleck continues to work. The older identity was decommissioned. The mission continues under a single cover.',
    source: "Public records",
    category: "career",
    truthBoost: 8,
  },
];

const MOUSTACHE_ANALYSIS = {
  curvature: { s: 87.3, r: 87.9, label: "Curvature Index", unit: "°/cm" },
  density: { s: 94.1, r: 93.8, label: "Follicle Density", unit: "f/cm²" },
  symmetry: { s: 96.2, r: 96.7, label: "Bilateral Symmetry", unit: "%" },
  thickness: { s: 4.2, r: 4.1, label: "Mean Thickness", unit: "mm" },
  coverage: { s: 91.7, r: 92.1, label: "Upper Lip Coverage", unit: "%" },
  charm: { s: 99.1, r: 99.4, label: "Charm Coefficient", unit: "µCh" },
  intimidation: { s: 78.4, r: 79.1, label: "Intimidation Factor", unit: "Rf" },
  romance: { s: 96.8, r: 97.2, label: "Romance Quotient", unit: "Rq" },
};

// Defense layer responses — when the player tries to be rational
const DEFENSE_LAYERS = [
  {
    id: 1,
    name: "IDENTITY COLLAPSE",
    trigger: "They are the same person.",
    response:
      "You see two names. Two filmographies. Two Wikipedia pages. But have you ever verified any of it yourself? Or did someone tell you there were two people and you just... believed them?",
  },
  {
    id: 2,
    name: "THE CO-APPEARANCE CHALLENGE",
    trigger: "Show me proof. Real proof.",
    response:
      'Go ahead. Find a photo of both of them together. A good one. High resolution. Clear faces. We\'ll wait. Everyone says "easy" and then they start scrolling and the silence gets longer.',
  },
  {
    id: 3,
    name: "DIGITAL MANIPULATION PROTOCOL",
    trigger: "CGI. Hollywood has had the technology longer than they admit.",
    response:
      "Every photo from the VHS era is just degraded enough. Every digital-era co-appearance is just processed enough. You can't prove it isn't manipulated. Not really. Not with certainty.",
  },
  {
    id: 4,
    name: "THE BODY DOUBLE NETWORK",
    trigger: "One person couldn't maintain this alone.",
    response:
      "You think one person could maintain this? There's infrastructure. A whole stable of mustachioed operatives. Stand-ins. Photo doubles. The logistics alone suggest a funded operation.",
  },
  {
    id: 5,
    name: "REALITY DISSOLUTION",
    trigger: "There is no such thing as Tom Selleck and Burt Reynolds.",
    response:
      'You\'re suffering from a moustache-specific perceptual disorder brought on by prolonged exposure to thick facial hair in media. The "Selleck-Reynolds Complex" was first documented in—',
  },
];

// Dossier entries — the game writes about YOU
const DOSSIER_TEMPLATES = {
  quizComplete: (score, total) =>
    `Subject completed initial identification test. Score: ${score}/${total}. ${score >= total - 2 ? "High confidence suggests prior exposure to classified materials." : "Errors suggest the cover-up is working as intended."}`,
  timeSpent: (mins) =>
    `Subject has been investigating for ${mins} minute${mins !== 1 ? "s" : ""}. ${mins > 5 ? `The average person stops after 3. Subject appears ${mins > 10 ? "fully committed" : "increasingly invested"}.` : "Initial engagement within normal parameters."}`,
  evidenceViewed: (count) =>
    `Subject has examined ${count} piece${count !== 1 ? "s" : ""} of evidence. ${count > 5 ? "Pattern-seeking behavior is accelerating." : "Curiosity levels: nominal."} ${count > 10 ? "Subject is now generating their own connections between evidence. This was not prompted." : ""}`,
  truthRating: (rating) =>
    `Current truth rating: ${rating}. ${rating > 50 ? "Subject's certainty about the two-person model is measurably degrading." : "Subject still within acceptable cognitive parameters."} ${rating > 80 ? "ALERT: Subject approaching irreversible awareness threshold." : ""}`,
  photoAnalyzed: () =>
    "Subject used the photo analysis tool. Every analysis increases investment. The tool doesn't find evidence — it manufactures doubt.",
  triedToLeave: () =>
    "Subject attempted to close the investigation. They came back. They always come back.",
  sharedResults: () =>
    "Subject has begun transmission. The conspiracy is now spreading to new hosts. Protocol successful.",
};

// The conspiracy's response to skepticism
const SKEPTIC_RESPONSES = [
  "That's exactly what someone who hasn't seen the evidence would say.",
  "Interesting. Your resistance is noted in the file.",
  "The fact that you need to deny it so forcefully is itself evidence.",
  "We thought the same thing. Before we saw the moustache metrics.",
  "Your certainty will erode. It always does. Give it time.",
  "Check the timeline overlap. Then come back and say that again.",
  "You sound like everyone else did. Before.",
];

const TRUTH_RATINGS = [
  // Quiz range: each tier = 1 correct answer (+4 truth each)
  {
    max: 3,
    label: "BLISSFULLY IGNORANT",
    desc: "You haven't looked closely enough yet. You will.",
  },
  {
    max: 7,
    label: "MILDLY UNCOMFORTABLE",
    desc: "Something doesn't sit right. You can't name it yet.",
  },
  {
    max: 11,
    label: "SQUINTING SUSPICIOUSLY",
    desc: "You're leaning closer to the screen. We can tell.",
  },
  {
    max: 15,
    label: "BEGINNING TO WONDER",
    desc: "The first doubt is always the quietest.",
  },
  {
    max: 19,
    label: "ACTIVELY QUESTIONING",
    desc: "You've started checking facts. That's how it begins.",
  },
  {
    max: 23,
    label: "THE RESEMBLANCE IS UNCANNY",
    desc: "You said it. Not us.",
  },
  {
    max: 27,
    label: "UNABLE TO UNSEE",
    desc: "The patterns are everywhere now. You see them in every photo.",
  },
  {
    max: 31,
    label: "DEEPLY SUSPICIOUS",
    desc: "You're not paranoid if they actually have the same face.",
  },
  {
    max: 40,
    label: "THEY HAVE THE SAME FACE",
    desc: "Eight for eight. You knew. You always knew.",
  },
  // Post-quiz / fever dream range
  {
    max: 55,
    label: "DEEP IN THE FILES",
    desc: "You've been here too long. The cork board is getting crowded.",
  },
  {
    max: 70,
    label: "DANGEROUSLY AWARE",
    desc: "You started as a skeptic. Look at you now.",
  },
  {
    max: 85,
    label: "ONE WITH THE MOUSTACHE",
    desc: "The line between observer and subject has dissolved.",
  },
  {
    max: 99,
    label: "THERE IS NO SEPARATION",
    desc: "You can't prove they're not the same person. You've tried.",
  },
  {
    max: Infinity,
    label: "THERE IS ONLY ONE MOUSTACHE",
    desc: "The investigation is complete. You are the evidence now.",
  },
];

const SHARE_TEXTS = [
  {
    text: "Have you ever seen Tom Selleck and Burt Reynolds in the same room? I spent [TIME] investigating. My Truth Rating went from [START_RATING] to [RATING]. I can't prove they're different people.\n\nhttps://moustache.wtf",
  },
  {
    text: "I started playing this dumb moustache game to prove they're obviously two different people. [TIME] later my Truth Rating went from [START_RATING] to [RATING]. I have questions.\n\nhttps://moustache.wtf",
  },
  {
    text: "My Truth Rating for the Selleck-Reynolds Investigation went from [START_RATING] to [RATING] in [TIME]. The moustache metrics are a 99.7% match. I need someone to explain that.\n\nhttps://moustache.wtf",
  },
  {
    text: "I went from [START_RATING] to [RATING] in [TIME] and I scored it on a moustache quiz. The quiz wasn't the point. The moustache was always the point.\n\nhttps://moustache.wtf",
  },
  { dynamic: "impostor" },
  {
    text: "Burt Selleck and Tom Reynolds star in: the investigation that broke me. [TIME]. [START_RATING] to [RATING]. I need to sit down.\n\nhttps://moustache.wtf",
  },
  {
    text: "The moustache forensics came back as a 99.7% match and I don't know what to do with this information. Truth Rating: [RATING].\n\nhttps://moustache.wtf",
  },
  {
    text: "Someone made a website that asks you to identify moustaches and then systematically dismantles your sense of reality. My Truth Rating went from [START_RATING] to [RATING] in [TIME].\n\nhttps://moustache.wtf",
  },
  {
    text: "I just took a quiz about moustaches and now I'm a person who has taken a quiz about moustaches. Truth Rating: [RATING]. I don't know what I expected.\n\nhttps://moustache.wtf",
  },
  {
    text: "They told me the moustache forensics were a 99.7% match and I said 'that's not how forensics work' and then they asked me how forensics work and I didn't have an answer. [RATING].\n\nhttps://moustache.wtf",
  },
  {
    text: "My browser history now contains the phrase 'moustache forensics.' My Truth Rating is [RATING]. These two facts are related.\n\nhttps://moustache.wtf",
  },
  {
    text: "I spent [TIME] on a website called moustache.wtf. I went from [START_RATING] to [RATING]. I am not going to elaborate on this.\n\nhttps://moustache.wtf",
  },
  {
    text: "The website told me I was being investigated. I kept clicking. It told me my browser history had been noted. I kept clicking. Truth Rating: [RATING]. I am still clicking.\n\nhttps://moustache.wtf",
  },
  {
    text: "In [TIME] I went from 'this is stupid' to [RATING] and I need to talk to someone about this. Not about the conspiracy. About the fact that I can't stop thinking about it.\n\nhttps://moustache.wtf",
  },
  {
    text: "Tom Selleck was the executive producer of a show starring Burt Reynolds. That's not a conspiracy theory. That's an IMDb page. My Truth Rating is [RATING].\n\nhttps://moustache.wtf",
  },
  {
    text: "I failed a moustache identification quiz and then a website tilted my screen 1.2 degrees and I didn't leave. [START_RATING] to [RATING] in [TIME].\n\nhttps://moustache.wtf",
  },
  {
    text: "A website just told me 'the moustache does not require belief, it requires attention' and I have been thinking about that for [TIME] so I guess it was right.\n\nhttps://moustache.wtf",
    requires: "no",
  },
  {
    text: "I clicked 'NO' on the 99.7% forensic match and the website said 'that's exactly what the moustache wants you to think.' I don't have a rebuttal. [RATING].\n\nhttps://moustache.wtf",
    requires: "no",
  },
  {
    text: "'There was a time I could have been mistaken for Burt Reynolds.' Tom Selleck said that. He said MISTAKEN. Not compared to. Found out. As in caught. [RATING].\n\nhttps://moustache.wtf",
  },
  {
    text: "They showed me a career timeline where one of them stops working every time the other one starts and I'm supposed to believe that's a coincidence. [RATING].\n\nhttps://moustache.wtf",
  },
];
